import Head from 'next/head'
import headerStyles from '../styles/Header.module.css'
import styles from '../styles/Home.module.css'
import {initializeIcons, Icon, Panel, PanelType, IconButton} from '@fluentui/react'
import Link from 'next/link'
import { useBoolean } from '@fluentui/react-hooks'
import Header from '../components/layouts/header'


initializeIcons();

export default function Home() {
  const [isOpen, { setTrue: openPanel, setFalse: dismissPanel }] = useBoolean(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header></Header>
        <div className={styles.grid}>
          <Link href="/line_counter" className={`${styles.card}`}>
            <h2>
              <Icon iconName='NumberedList'/>
            </h2>
            <h2>Line Counter</h2>
          </Link>

          <Link href="/docment_search" className={styles.card}>
            <h2  >
              <Icon iconName='DocumentSearch'/>
            </h2>
            <h2>Search Docment</h2>
          </Link>
        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
