import Head from 'next/head'
import headerStyles from '../styles/Header.module.css'
import styles from '../styles/Home.module.css'
import {initializeIcons, Icon, Panel, PanelType, IconButton} from '@fluentui/react'
import Link from 'next/link'
import { useBoolean } from '@fluentui/react-hooks';


initializeIcons();

export default function Home() {
  const [isOpen, { setTrue: openPanel, setFalse: dismissPanel }] = useBoolean(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Panel
          isLightDismiss
          isBlocking={false}
          isOpen={isOpen}
          onDismiss={dismissPanel}
          type={PanelType.smallFixedNear}
          hasCloseButton={false}
        >
          <div className={`${headerStyles.menu}`} onClick={dismissPanel}>
            <IconButton iconProps={{iconName: 'CollapseMenu'}} title={"menu"}/>
          </div>

          <Link href="/line_counter/line_counter" className={`${headerStyles.hamburger_item}`}>
              <Icon iconName='NumberedList' className={`${headerStyles.hamburger_item__icon}`}/>
              Line Counter
          </Link>

          <Link href="/docment_search/docment_search" className={`${headerStyles.hamburger_item}`}>
              <Icon iconName='DocumentSearch' className={`${headerStyles.hamburger_item__icon}`}/>
              Search Docment
          </Link>

        </Panel>

        <div className={`${headerStyles.tab_header}`}>
          <div className={`${headerStyles.hamburger_menu}`} onClick={openPanel}>
            <IconButton iconProps={{iconName: 'CollapseMenu'}} title={"menu"}/>
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="/line_counter/line_counter" className={`${styles.card}`}>
            <h2>
              <Icon iconName='NumberedList'/>
            </h2>
            <h2>Line Counter</h2>
          </Link>

          <Link href="/docment_search/docment_search" className={styles.card}>
            <h2  >
              <Icon iconName='DocumentSearch'/>
            </h2>
            <h2>Search Docment</h2>
          </Link>
        </div>

      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
