name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: initialize
      run: sudo apt install libgtk-3-dev
      run: sudo apt install libsoup2.4-dev
    - name: Run tests
      run: cargo test --verbose --manifest-path src-tauri/Cargo.toml -- --test-threads=1
    - name: Build
      run: cargo build --verbose  --manifest-path src-tauri/Cargo.toml
